apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-1
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: project-1
  source:
     path: helm/nginx
     repoURL: https://github.com/masoudkavehie/application-.git
     targetRevision: main
